name: Test on push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install libxcb-icccm4
        run: |
          sudo apt-get install libxcb-icccm4
          sudo apt update
      - name: Run tests
        run: |
          export QT_DEBUG_PLUGINS=1
          python -m unittest